/* This file has general constants declarations */
export const ACCESS_TOKEN_KEY = 'access_token'

export const PROTECTED_URLS = ['/dashboard']

export const ADDITIONAL = {
  LEADS: {
    SURVEY_IMAGE_LABELS: [
      "Do not use photo",
      "Boiler and its pipework ( Old )",
      "Dataplate including back boiler ( Old )",
      "Flu ( Old )",
      "Filter ( Old )",
      "Gas meter",
      "Electric meter",
      "Eletric meter fuse box",
      "Floor plan",
      "EST form",
      "EPC form",
      "Survey form",
      "Proof of ownership",
      "Proof of benefit",
      "Proof of address or utility bill",
      "Relationship declaration",
      "Bedroom picture",
      "Kitchen picture",
      "Living room picture",
      "Conservity",
      "Bathroom picture",
      "Extractor fan",
      "Hallway",
      "Cavity wall evidence",
      "Wall thickness picture",
      "All radiator picture",
      "TRV pictures",
      "Front elevation",
      "Back elevation",
      "Side elevation picture",
      "Cylinder Picture",
      "Evidence of secondary heating",
      "Programmer and room thermostats",
      "Loft pictures",
      "Loft measurement",
      "Windows",
      "Windows thickness",
      "Evidence of ventilation",
      "Survey coordinates",
      "Extras"
    ],
    INSTALLATION_IMAGE_LABELS: [
      'Do not use photo',
      'Heating System ( Old )',
      'Data plate ( Old )',
      'Flue ( Old )',
      'Boiler ( Old )',
      'Empty wall for boiler',
      'Data plate ( New )',
      'Earth Bonding Wire',
      'Analyser',
      'Condensate pipe',
      'PRV',
      'Gas meter',
      'Electric meter & Electric Fuse box',
      'Empty wall for radiator',
      'Radiator ( New )',
      'Radiators',
      'NO TRV',
      'TRV ( New )',
      'Gas safe certificate',
      'Benchmark form',
      'Heating control device',
      'CMA (Carbon Monoxide Alarm)',
      'Receiver',
      'Fuse spur',
      'Filter',
      'Tank without insulation or jacket',
      'BOILER front side sticker',
      'Extras',
      'Datamatch screenshot',
      'TTZC',
      'Bypass',
      'New Flue'
    ]
  }
}
