name: "MEG FRONTEND"

on:
  push:
    branches: ["develop"]
  pull_request:
    types:
      - closed

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Send In Progress Notification
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "started"
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /data/www/megcrm.co.uk/megcrm-fe
            git stash
            git pull
            pnpm i
            npm run build
      - name: Send Success Notification
        if: success()
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "success"
      - name: Send Failure Notification
        if: failure()
        uses: imfaisii/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: "failure"
